En utilisant numpy:

Ex 1 :Addition
Écrire un programme pour lire les éléments de deux matrices et ajoutez les deux matrices dans la troisième.

La somme de deux matrices de taille (m,n), $(A_{ij}) et (B_{ij}) notée $A+B$  est à nouveau une matrice (C_{ij}) de taille (m,n), obtenue en additionnant les éléments correspondants: $c_{ij}=a_{ij}+b_{ij}$


In [1]:
import numpy as np

A = np.array([ [3,1,3], [4,3,-1], [2,1,2] ])
B = np.array([ [1,-1,3], [2,1,3], [1,2,3] ])

C = A+B 
print("A : ", A)
print("A : ", B)
print("A + B : ", C)

A :  [[ 3  1  3]
 [ 4  3 -1]
 [ 2  1  2]]
A :  [[ 1 -1  3]
 [ 2  1  3]
 [ 1  2  3]]
A + B :  [[4 0 6]
 [6 4 2]
 [3 3 5]]


Ex2 :Multiplication
Écrire un programme pour lire les éléments de deux matrices, puis multipliez les deux matrices dans la troisième.

Deux matrices ne peuvent être multipliées que si le nombre de colonnes de la première matrice est le même que le nombre de lignes de la seconde matrice.

Si $ A=(a_{ij})$ est une matrice de taille (m,n), $ B=(b_{ij})$ et est une matrice de taille (n,p), alors leur produit, noté $AB=(c_{ij})$ est une matrice de taille (m,p) définie par :
$$\forall i,j : c_{ij}=\sum_{k=i}^{n} a_{ik}*b_{kj}$$

In [3]:
A = np.array([ [3, 1, 4], [2, 2, -1], [1, 2, 2] ])
B = np.array([ [2, -1, 3], [2, 1, 3], [1, 2, 3] ])
 
C = A.dot(B)
 
print("A : ", A)
print("B : ", B)
print("A * B : ", C)

A :  [[ 3  1  4]
 [ 2  2 -1]
 [ 1  2  2]]
B :  [[ 2 -1  3]
 [ 2  1  3]
 [ 1  2  3]]
A * B :  [[12  6 24]
 [ 7 -2  9]
 [ 8  5 15]]


Ex 3: Matrice de Markov

Une matrice de Markov est une matrice carrée dont chaque élément est un réel compris entre 0 et 1 et dont la somme des éléments de chaque ligne vaut 1. Cela correspond, en probabilité, à la matrice de transition d'une chaîne de Markov finie.

Une matrice est dite bistochastique (ou doublement stochastique) si la somme des éléments de chaque ligne et de chaque colonne vaut 1.

1. Ecrire une fonction eststochastique(P) qui permet de vérifier est ce que la matrice P est stochastique ou non
2. Ecrire une fonction estbistochastique(P) qui permet de vérifier est ce que la matrice P est bistochastique ou non
3. Ecrire une fonction vecteurstable(G, h) qui permet de vérifier est ce que h est un vecteur stable de G ou non



In [4]:
def eststochastique(P):
    nl = len(P)  # nb lignes
    nc = len(P[0])  # nb colonnes
 
    etat = True
    for i in range(nl):
        s = 0
        for j in range(nc):
            s += P[i][j]
        if s != 1:
            etat = False
            break
    return etat
 
 
def estbistochastique(P):
    nl = len(P)  # nb lignes
    nc = len(P[0])  # nb colonnes
 
    etat = True
    if eststochastique(P):
        for j in range(nc):
            s = 0
            for i in range(nl):
                s += P[i][j]
            if s != 1:
                etat = False
                break
    return etat
 
 
def vecteurstable(G, h):
    nl = len(G)  # nblignes
    nc = len(G[0])  # nb colonnes
    etat = True
    if eststochastique(G):
        for j in range(nc):
            s = 0
            for i in range(nl):
                s += h[i] * G[i][j]
            if s != h[j]:
                etat = False
                break
    else:
        etat = False
    return etat

Ex 4: Transposer

Programmer une fonction qui, étant donné une matrice à deux dimensions A, retourne lamatrice B dont la première colonne est la première ligne de A, la seconde la deuxième ligne de A, etc. B s’appelle la transposée de A.

In [5]:
A = np.array([ [3, 1, 5], [9, 8, -1], [18, 12, 2] ])
 
C = A.transpose()
 
print("A : ", A)
print("Transposée de A : ", C)

A :  [[ 3  1  5]
 [ 9  8 -1]
 [18 12  2]]
Transposée de A :  [[ 3  9 18]
 [ 1  8 12]
 [ 5 -1  2]]


Ex 5: Permutations
1. $M$ désignant une matrice quelconque d’entiers à $l_i$ lignes et $co$ colonnes, $n$ un entier quelconque, programmer une fonction qui retourne la matrice $Sortie$ qui empile verticalement les $co+1$ matrices obtenues en adjoignant à $M$ une colonne $A$ à $li$ lignes dont tousles éléments sont égaux à $n$, $A$ étant placée d’abord devant $M$, puis entre la première et deuxième colonne de $M^a$,etc, jusqu’à ce que $A$ devienne sa dernière colonne. La matriceobtenue  aura $co+1$ colonnes et $(n+1)$ $li$ lignes

2. Écrire toutes les permutations de(1, ..., n)

In [6]:
def apply_permutation(A,perm,N):
    B=np.empty_like(A) # A est une matrice NxN d'entiers dans range(N)
    for i in range(N):
            B[A[:]==i]=perm[i] # perm est une permutation de range(N)
    return B

#appeler la fonction dans un for